In [1]:
import pandas as pd

In [2]:
yearly = pd.read_csv('./data/연간_df_with_업종.csv')

In [4]:
yearly = yearly.drop('Unnamed: 0',axis = 1)

In [8]:
yearly_방송통신 = yearly[yearly['업종'] == '텔레비전 방송업']
yearly_방송통신

           회사이름    회사코드   옥수치17/12    옥수치18/12   옥수치19/12   옥수치20/09        업종
6        LG헬로비전   37560   4.194235    3.836725   1.833424   1.622291  텔레비전 방송업
82        GS홈쇼핑   28150  36.883320   34.791455  27.883951  23.725910  텔레비전 방송업
369      CJ ENM   35760   9.732940    3.887620   7.767942   5.317552  텔레비전 방송업
550      한국경제TV   39340  56.521739  105.442177  66.183575  65.887850  텔레비전 방송업
599         SBS   34120   2.459555    0.795880   1.561145   4.305750  텔레비전 방송업
600   SBS미디어홀딩스  101060  -1.696922    0.799290   2.543720  -4.240283  텔레비전 방송업
701       현대퓨처넷  126560  12.785270   10.967590   9.800625   7.257871  텔레비전 방송업
1005        KMH  122450   8.096280    6.073372   7.226783   8.434475  텔레비전 방송업
1300        KNN   58400   9.287257    8.863636   8.457143   3.102625  텔레비전 방송업
1658       씨씨에스   66790  -1.272265  -11.314985   1.320132   0.403226  텔레비전 방송업
1855  케이티스카이라이프   53210  13.870493   12.322187  13.567937  12.581217  텔레비전 방송업
2364        티비씨   33830   6.413302    5.701754  10.216110  -0.232558  텔레비전 방송업

In [10]:
quarter = pd.read_csv('./data/분기_df_with_업종.csv')
quarter = quarter.drop('Unnamed: 0',axis = 1)
quarter_방송통신 = quarter[quarter['업종'] == '텔레비전 방송업']
quarter_방송통신.mean()

회사코드        61435.833333
옥수치19/12        4.092458
옥수치20/03        1.816970
옥수치20/06        4.398062
옥수치20/09        4.527754
dtype: float64

In [11]:
import FinanceDataReader as fdr
from datetime import datetime

def full_name_of_date(input_date):
    if len(input_date) == 10:
        return input_date
    elif len(input_date) == 7:
        return input_date + '-01'
    elif len(input_date) == 4:
        return input_date + '-01-01'
    else:
        print("뭔가이상한데")


def print_stockData(stock_code,start_day,end_day = None):
    if end_day is None:
        df = fdr.DataReader(stock_code, start_day)
        print(df)
    else:
        df = fdr.DataReader(stock_code, start_day,end_day)
        print(df)



def get_stockData_2_csv(stock_code,start_day,end_day = None):
    if end_day is None:
        df = fdr.DataReader(stock_code, start_day)
        end_day = datetime.today().strftime("%Y-%m-%d")
        df.to_csv('data/'+ stock_code+'_'+full_name_of_date(start_day)+ '_' + full_name_of_date(end_day)+'.csv')
    else:
        df = fdr.DataReader(stock_code, start_day,end_day)
        df.to_csv('data/'+ stock_code+'_'+full_name_of_date(start_day)+ '_' + full_name_of_date(end_day)+'.csv')
        print('\n'+str(len(df))+'row saved_as_csv\n' )

def get_stockData_2_dataframe(stock_code,start_day,end_day = None):
    if end_day is None:
        df = fdr.DataReader(stock_code, start_day)
        return df

    else:
        df = fdr.DataReader(stock_code, start_day,end_day)
        return df

In [12]:
pip install pykrx

Collecting pykrx
  Downloading pykrx-1.0.7-py3-none-any.whl (55 kB)
Requirement already satisfied: requests in c:\python\anaconda3\lib\site-packages (from pykrx) (2.25.1)
Requirement already satisfied: pandas in c:\python\anaconda3\lib\site-packages (from pykrx) (1.1.5)
Requirement already satisfied: numpy in c:\python\anaconda3\lib\site-packages (from pykrx) (1.19.2)
Requirement already satisfied: xlrd in c:\python\anaconda3\lib\site-packages (from pykrx) (2.0.1)
Collecting datetime
  Downloading DateTime-4.3-py2.py3-none-any.whl (60 kB)
Requirement already satisfied: pytz in c:\python\anaconda3\lib\site-packages (from datetime->pykrx) (2020.5)
Collecting deprecated
  Downloading Deprecated-1.2.11-py2.py3-none-any.whl (9.1 kB)
Requirement already satisfied: wrapt<2,>=1.10 in c:\python\anaconda3\lib\site-packages (from deprecated->pykrx) (1.12.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\python\anaconda3\lib\site-packages (from pandas->pykrx) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\python\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->pykrx) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\anaconda3\lib\site-packages (from requests->pykrx) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\python\anaconda3\lib\site-packages (from requests->pykrx) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\python\anaconda3\lib\site-packages (from requests->pykrx) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\anaconda3\lib\site-packages (from requests->pykrx) (1.26.2)
Collecting zope.interface
  Downloading zope.interface-5.2.0-cp37-cp37m-win_amd64.whl (196 kB)
Requirement already satisfied: setuptools in c:\python\anaconda3\lib\site-packages (from zope.interface->datetime->pykrx) (51.1.2.post20210112)
Installing collected packages: zope.interface, deprecated, datetime, pykrx
Successfully installed datetime-4.3 deprecated-1.2.11 pykrx-1.0.7 zope.interface-5.2.0
Note: you may need to restart the kernel to use updated packages.

In [13]:
from pykrx import stock
df = stock.get_market_cap_by_ticker("20210202")
print(df)

            종가             시가총액       거래량           거래대금       상장주식수
티커
005930   56600  337889692330000  26907844  1541223383000  5969782550
000660   79900   58167388963500   2710477   219064698950   728002365
035420  290000   47636384550000    939833   275981100000   164263395
207940  682000   45124530000000    251134   174660762000    66165000
051910  611000   43131921573000    820454   512035157000    70592343
...        ...              ...       ...            ...         ...
224020     910       2457000000         0              0     2700000
267810    1450       2243150000      2003        2554350     1547000
238500     443       2074199538      4208        1777904     4682166
344860    1115       2073900000         0              0     1860000
225860     159       1805936628     10753        1819284    11358092

[2507 rows x 5 columns]

In [16]:
quarter_방송통신['회사코드'] =  quarter_방송통신['회사코드'].apply(lambda x : str(x).zfill(6))
yearly_방송통신['회사코드'] =  yearly_방송통신['회사코드'].apply(lambda x : str(x).zfill(6))
yearly_방송통신
result_quarter = pd.merge(quarter_방송통신,df,on=['회사코드','티커'])
result_quarter

C:\Python\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Python\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

KeyError: '회사코드'

In [27]:
result_yearly = pd.merge(yearly_방송통신,df,left_on='회사코드', right_on='티커')
result_yearly.rename(columns = {'시가총액': '시가총액_억'}, inplace = True)
result_yearly['시가총액_억'] = round(result_yearly['시가총액_억'] / 100000000,3)
result_yearly

,회사이름,회사코드,옥수치17/12,옥수치18/12,옥수치19/12,옥수치20/09,업종,종가,시가총액_억,거래량,거래대금,상장주식수
0,LG헬로비전,037560,4.194235,3.836725,1.833424,1.622291,텔레비전 방송업,3785,2931.364,73986,281523895,77446865
1,GS홈쇼핑,028150,36.883320,34.791455,27.883951,23.725910,텔레비전 방송업,138700,9102.188,41744,5903087400,6562500
2,CJ ENM,035760,9.732940,3.887620,7.767942,5.317552,텔레비전 방송업,131500,28836.838,69820,9303782500,21929154
3,한국경제TV,039340,56.521739,105.442177,66.183575,65.887850,텔레비전 방송업,4990,1147.700,53020,265201130,23000000
4,SBS,034120,2.459555,0.795880,1.561145,4.305750,텔레비전 방송업,15750,2874.782,58694,941979600,18252582
5,SBS미디어홀딩스,101060,-1.696922,0.799290,2.543720,-4.240283,텔레비전 방송업,1645,2301.292,13451,22238425,139896190
6,현대퓨처넷,126560,12.785270,10.967590,9.800625,7.257871,텔레비전 방송업,3115,3516.106,202748,641123440,112876596
7,KMH,122450,8.096280,6.073372,7.226783,8.434475,텔레비전 방송업,24250,5496.986,713344,17432322150,22667982
8,KNN,058400,9.287257,8.863636,8.457143,3.102625,텔레비전 방송업,1910,2529.408,8673115,17250891065,132429720
9,씨씨에스,066790,-1.272265,-11.314985,1.320132,0.403226,텔레비전 방송업,846,388.958,0,0,45976167
10,케이티스카이라이프,053210,13.870493,12.322187,13.567937,12.581217,텔레비전 방송업,9480,4533.522,135555,1309493470,47821966
11,티비씨,033830,6.413302,5.701754,10.216110,-0.232558,텔레비전 방송업,900,900.000,240908,217537254,100000000

In [25]:
result_quarter = pd.merge(quarter_방송통신,df,left_on='회사코드', right_on='티커')
result_quarter.rename(columns = {'시가총액': '시가총액_억'}, inplace = True)
result_quarter['시가총액_억'] = round(result_quarter['시가총액_억'] / 100000000,3)
result_quarter

,회사이름,회사코드,옥수치19/12,옥수치20/03,옥수치20/06,옥수치20/09,업종,종가,시가총액_억,거래량,거래대금,상장주식수
0,LG헬로비전,037560,0.199023,0.471121,0.603374,0.569659,텔레비전 방송업,3785,2931.364,73986,281523895,77446865
1,GS홈쇼핑,028150,6.907668,6.895037,9.067075,8.115632,텔레비전 방송업,138700,9102.188,41744,5903087400,6562500
2,CJ ENM,035760,1.231222,1.150225,2.178494,2.049654,텔레비전 방송업,131500,28836.838,69820,9303782500,21929154
3,한국경제TV,039340,11.594203,10.714286,24.285714,30.841121,텔레비전 방송업,4990,1147.700,53020,265201130,23000000
4,SBS,034120,4.026762,-0.787302,0.211193,4.950912,텔레비전 방송업,15750,2874.782,58694,941979600,18252582
5,SBS미디어홀딩스,101060,3.603604,-2.678571,-1.135074,-0.471143,텔레비전 방송업,1645,2301.292,13451,22238425,139896190
6,현대퓨처넷,126560,1.489311,2.599611,2.840353,1.922615,텔레비전 방송업,3115,3516.106,202748,641123440,112876596
7,KMH,122450,2.237244,0.788741,4.241586,3.426026,텔레비전 방송업,24250,5496.986,713344,17432322150,22667982
8,KNN,058400,2.514286,-0.619579,2.962085,0.715990,텔레비전 방송업,1910,2529.408,8673115,17250891065,132429720
9,씨씨에스,066790,1.650165,0.000000,0.000000,0.000000,텔레비전 방송업,846,388.958,0,0,45976167
10,케이티스카이라이프,053210,3.636364,4.997935,5.352748,2.677692,텔레비전 방송업,9480,4533.522,135555,1309493470,47821966
11,티비씨,033830,10.019646,-1.727862,2.169197,-0.465116,텔레비전 방송업,900,900.000,240908,217537254,100000000

In [30]:

for stock_code in result_quarter['회사코드']:
    try:
        html = open('./html/'+stock_code+'.html','r',encoding='utf-8')
        bsObject = BeautifulSoup(html, "html.parser")
    except:
        print('시발')
        continue
    fi1 = Financial_Statements(bsObject,stock_code)
    result_yearly.loc[result_yearly['회사코드'] == stock_code,'영업이익'] = fi1.분기_포괄손익계산서_df.loc['영업이익']['2020/09']
    result_quarter.loc[result_quarter['회사코드'] == stock_code,'영업이익'] = fi1.분기_포괄손익계산서_df.loc['영업이익']['2020/09']

037560가 종료
028150가 종료
035760가 종료
039340가 종료
034120가 종료
101060가 종료
126560가 종료
122450가 종료
058400가 종료
066790가 종료
053210가 종료

In [33]:
result_quarter.rename(columns = {'영업이익': '영업이익_억'}, inplace = True)
result_yearly.rename(columns = {'영업이익': '영업이익_억'}, inplace = True)
result_quarter = result_quarter.drop(['상장주식수','거래대금'],axis = 1)
result_yearly = result_yearly.drop(['상장주식수','거래대금'],axis = 1)
result_yearly

,회사이름,회사코드,옥수치17/12,옥수치18/12,옥수치19/12,옥수치20/09,업종,종가,시가총액_억,거래량,영업이익_억
0,LG헬로비전,037560,4.194235,3.836725,1.833424,1.622291,텔레비전 방송업,3785,2931.364,73986,92.0
1,GS홈쇼핑,028150,36.883320,34.791455,27.883951,23.725910,텔레비전 방송업,138700,9102.188,41744,379.0
2,CJ ENM,035760,9.732940,3.887620,7.767942,5.317552,텔레비전 방송업,131500,28836.838,69820,710.0
3,한국경제TV,039340,56.521739,105.442177,66.183575,65.887850,텔레비전 방송업,4990,1147.700,53020,66.0
4,SBS,034120,2.459555,0.795880,1.561145,4.305750,텔레비전 방송업,15750,2874.782,58694,353.0
5,SBS미디어홀딩스,101060,-1.696922,0.799290,2.543720,-4.240283,텔레비전 방송업,1645,2301.292,13451,-8.0
6,현대퓨처넷,126560,12.785270,10.967590,9.800625,7.257871,텔레비전 방송업,3115,3516.106,202748,80.0
7,KMH,122450,8.096280,6.073372,7.226783,8.434475,텔레비전 방송업,24250,5496.986,713344,223.0
8,KNN,058400,9.287257,8.863636,8.457143,3.102625,텔레비전 방송업,1910,2529.408,8673115,6.0
9,씨씨에스,066790,-1.272265,-11.314985,1.320132,0.403226,텔레비전 방송업,846,388.958,0,0.0
10,케이티스카이라이프,053210,13.870493,12.322187,13.567937,12.581217,텔레비전 방송업,9480,4533.522,135555,136.0
11,티비씨,033830,6.413302,5.701754,10.216110,-0.232558,텔레비전 방송업,900,900.000,240908,-2.0

In [35]:
result_quarter['1억원을_만들기위한_투자금'] = result_quarter['시가총액_억'] / result_quarter['영업이익_억']
result_quarter

,회사이름,회사코드,옥수치19/12,옥수치20/03,옥수치20/06,옥수치20/09,업종,종가,시가총액_억,거래량,영업이익_억,1억원을_만들기위한_투자금
0,LG헬로비전,037560,0.199023,0.471121,0.603374,0.569659,텔레비전 방송업,3785,2931.364,73986,92.0,31.862652
1,GS홈쇼핑,028150,6.907668,6.895037,9.067075,8.115632,텔레비전 방송업,138700,9102.188,41744,379.0,24.016327
2,CJ ENM,035760,1.231222,1.150225,2.178494,2.049654,텔레비전 방송업,131500,28836.838,69820,710.0,40.615265
3,한국경제TV,039340,11.594203,10.714286,24.285714,30.841121,텔레비전 방송업,4990,1147.700,53020,66.0,17.389394
4,SBS,034120,4.026762,-0.787302,0.211193,4.950912,텔레비전 방송업,15750,2874.782,58694,353.0,8.143858
5,SBS미디어홀딩스,101060,3.603604,-2.678571,-1.135074,-0.471143,텔레비전 방송업,1645,2301.292,13451,-8.0,-287.661500
6,현대퓨처넷,126560,1.489311,2.599611,2.840353,1.922615,텔레비전 방송업,3115,3516.106,202748,80.0,43.951325
7,KMH,122450,2.237244,0.788741,4.241586,3.426026,텔레비전 방송업,24250,5496.986,713344,223.0,24.650161
8,KNN,058400,2.514286,-0.619579,2.962085,0.715990,텔레비전 방송업,1910,2529.408,8673115,6.0,421.568000
9,씨씨에스,066790,1.650165,0.000000,0.000000,0.000000,텔레비전 방송업,846,388.958,0,0.0,inf
10,케이티스카이라이프,053210,3.636364,4.997935,5.352748,2.677692,텔레비전 방송업,9480,4533.522,135555,136.0,33.334721
11,티비씨,033830,10.019646,-1.727862,2.169197,-0.465116,텔레비전 방송업,900,900.000,240908,-2.0,-450.000000

In [26]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup


class Financial_Statements:
    def clean_index(self,index_of_thing):
        result = []
        for i in index_of_thing:
            a = i.get_text()
            if '펼치기' not in a:
                result.append(a.replace('\n','').lstrip().replace('\xa0','_'))
            else:
                result.append(a.replace('\n','')[:-14].lstrip())
        return result
    def clean_columns(self,columns_of_thing):
        result = []
        for i in columns_of_thing:
            result.append(i.get_text())
        return result
    def clean_values(self,values_of_thing):
        result = []
        for i in values_of_thing:
            try:
                result.append(float(i.get_text().replace(',','')))
            except:
                result.append(0)
        return result

    def __init__(self,bsObject,stock_codes):
        self.stock_code = stock_codes

        연간_포괄손익계산서_columns = self.clean_columns(bsObject.select('#divSonikY > table > thead > tr > th')[1:])
        연간_포괄손익계산서_index = self.clean_index(bsObject.select('#divSonikY > table > tbody > tr > th'))# 인덱스 완료
        연간_포괄손익계산서_values= np.reshape(self.clean_values(bsObject.select('#divSonikY > table > tbody > tr >td')),(len(연간_포괄손익계산서_index),len(연간_포괄손익계산서_columns)))
        self.연간_포괄손익계산서_df = pd.DataFrame(index = 연간_포괄손익계산서_index, columns = 연간_포괄손익계산서_columns,data = 연간_포괄손익계산서_values)

        분기_포괄손익계산서_columns = self.clean_columns(bsObject.select('#divSonikQ > table > thead > tr > th')[1:])
        분기_포괄손익계산서_index = self.clean_index(bsObject.select('#divSonikQ > table > tbody > tr > th'))# 인덱스 완료
        분기_포괄손익계산서_values= np.reshape(self.clean_values(bsObject.select('#divSonikQ > table > tbody > tr >td')),(len(분기_포괄손익계산서_index),len(분기_포괄손익계산서_columns)))
        self.분기_포괄손익계산서_df = pd.DataFrame(index = 분기_포괄손익계산서_index, columns = 분기_포괄손익계산서_columns,data = 분기_포괄손익계산서_values)



        연간_재무상태표_columns = self.clean_columns(bsObject.select('#divDaechaY > table > thead > tr > th')[1:])
        연간_재무상태표_index = self.clean_index(bsObject.select('#divDaechaY > table > tbody > tr > th'))# 인덱스 완료
        연간_재무상태표_values= np.reshape(self.clean_values(bsObject.select('#divDaechaY > table > tbody > tr >td')),(len(연간_재무상태표_index),len(연간_재무상태표_columns)))
        self.연간_재무상태표_df = pd.DataFrame(index = 연간_재무상태표_index, columns = 연간_재무상태표_columns,data = 연간_재무상태표_values)

        분기_재무상태표_columns = self.clean_columns(bsObject.select('#divDaechaQ > table > thead > tr > th')[1:])
        분기_재무상태표_index = self.clean_index(bsObject.select('#divDaechaQ > table > tbody > tr > th'))# 인덱스 완료
        분기_재무상태표_values= np.reshape(self.clean_values(bsObject.select('#divDaechaQ > table > tbody > tr >td')),(len(분기_재무상태표_index),len(분기_재무상태표_columns)))
        self.분기_재무상태표_df = pd.DataFrame(index = 분기_재무상태표_index, columns = 분기_재무상태표_columns,data = 분기_재무상태표_values)


        '''
        연간_현금흐름표_columns = self.clean_columns(bsObject.select('#divCashY > table > thead > tr > th')[1:])
        연간_현금흐름표_index = self.clean_index(bsObject.select('#divCashY > table > tbody > tr > th'))# 인덱스 완료
        연간_현금흐름표_values= np.reshape(self.clean_values(bsObject.select('#divCashY > table > tbody > tr >td')),(len(연간_현금흐름표_index),len(연간_현금흐름표_columns)))
        self.연간_현금흐름표_df = pd.DataFrame(index = 연간_현금흐름표_index, columns = 연간_현금흐름표_columns,data = 연간_현금흐름표_values)

        분기_현금흐름표_columns = self.clean_columns(bsObject.select('#divCashQ > table > thead > tr > th')[1:])
        분기_현금흐름표_index = self.clean_index(bsObject.select('#divCashQ > table > tbody > tr > th'))# 인덱스 완료
        분기_현금흐름표_values= np.reshape(self.clean_values(bsObject.select('#divCashQ > table > tbody > tr >td')),(len(분기_현금흐름표_index),len(분기_현금흐름표_columns)))
        self.분기_현금흐름표_df = pd.DataFrame(index = 분기_현금흐름표_index, columns = 분기_현금흐름표_columns,data = 분기_현금흐름표_values)
        '''

    def 옥_수식_연간(self):
        date_columns = self.연간_재무상태표_df.columns
        유동금융자산 = 0
        현금및현금성자산 = 0
        투자부동산 = 0
        장기금융자산 = 0
        관계기업등지분관련투자자산 = 0
        기타금융업자산 = 0
        자산_비영업포함 = 0

        영업이익 = 0
        #비영업이익
        try:
            유동금융자산 = self.연간_재무상태표_df.loc['유동금융자산']
        except:
            유동금융자산 = 0

        try:
            현금및현금성자산 = self.연간_재무상태표_df.loc['현금및현금성자산']
        except:
            현금및현금성자산 = 0

        try:
            투자부동산 = self.연간_재무상태표_df.loc['투자부동산']
        except:
            투자부동산 = 0

        try:
            장기금융자산 = self.연간_재무상태표_df.loc['장기금융자산']
        except:
            장기금융자산 = 0

        try:
            관계기업등지분관련투자자산 = self.연간_재무상태표_df.loc['관계기업등지분관련투자자산']
        except:
            관계기업등지분관련투자자산 = 0

        try:
            기타금융업자산 = self.연간_재무상태표_df.loc['기타금융업자산']
        except:
            기타금융업자산 = 0

        try:
            자산_비영업포함 = self.연간_재무상태표_df.loc['자산']
        except:
            자산_비영업포함 = 0
        
        try:
            영업이익 = self.연간_포괄손익계산서_df.loc['영업이익'][date_columns]
        except:
            return [np.nan,np.nan,np.nan,np.nan]
        
        영업이익 = 영업이익.astype(int)
        #영업이익 = self.연간_포괄손익계산서_df.loc['영업이익'][date_columns].astype(int)
        try:
            영업자산 = (자산_비영업포함 -유동금융자산-현금및현금성자산-투자부동산-장기금융자산-관계기업등지분관련투자자산 - 기타금융업자산).astype(int)
        except:
            return [np.nan,np.nan,np.nan,np.nan]

        ock_수식 = 영업이익/영업자산 * 100
        return ock_수식


        '''
        print(self.stock_code)

        #비영업자산
        date_columns = self.연간_재무상태표_df.columns
        유동금융자산 = self.연간_재무상태표_df.loc['유동금융자산']
        현금및현금성자산 = self.연간_재무상태표_df.loc['현금및현금성자산']
        투자부동산 = self.연간_재무상태표_df.loc['투자부동산']
        장기금융자산 = self.연간_재무상태표_df.loc['장기금융자산']
        관계기업등지분관련투자자산 = self.연간_재무상태표_df.loc['관계기업등지분관련투자자산']
        기타금융업자산 = self.연간_재무상태표_df.loc['기타금융업자산']
        자산_비영업포함 = self.연간_재무상태표_df.loc['자산']


        영업자산 = 자산_비영업포함 -유동금융자산-현금및현금성자산-투자부동산-장기금융자산-관계기업등지분관련투자자산 - 기타금융업자산
        영업이익 = self.연간_포괄손익계산서_df.loc['영업이익'][date_columns]
        ock_수식 = 영업이익.astype(int)/영업자산.astype(int) * 100
        return ock_수식
'''

    def 옥_수식_분기(self):
        date_columns = self.분기_재무상태표_df.columns
        print(self.stock_code)
        유동금융자산 = 0
        현금및현금성자산 = 0
        투자부동산 = 0
        장기금융자산 = 0
        관계기업등지분관련투자자산 = 0
        기타금융업자산 = 0
        자산_비영업포함 = 0

        영업이익 = 0
        #비영업이익
        try:
            유동금융자산 = self.분기_재무상태표_df.loc['유동금융자산']
        except:
            유동금융자산 = 0

        try:
            현금및현금성자산 = self.분기_재무상태표_df.loc['현금및현금성자산']
        except:
            현금및현금성자산 = 0

        try:
            투자부동산 = self.분기_재무상태표_df.loc['투자부동산']
        except:
            투자부동산 = 0

        try:
            장기금융자산 = self.분기_재무상태표_df.loc['장기금융자산']
        except:
            장기금융자산 = 0

        try:
            관계기업등지분관련투자자산 = self.분기_재무상태표_df.loc['관계기업등지분관련투자자산']
        except:
            관계기업등지분관련투자자산 = 0

        try:
            기타금융업자산 = self.분기_재무상태표_df.loc['기타금융업자산']
        except:
            기타금융업자산 = 0

        try:
            자산_비영업포함 = self.분기_재무상태표_df.loc['자산']
        except:
            자산_비영업포함 = 0
        '''
        try:
            영업이익 = self.분기_포괄손익계산서_df.loc['영업이익'][date_columns].astype(int)
        except:
            print('영업이익 이상함')
            영업이익 = 0
        '''



        try:
            영업이익 = self.분기_포괄손익계산서_df.loc['영업이익'][date_columns]
        except:
            return [np.nan,np.nan,np.nan,np.nan] 

        영업이익 = 영업이익.astype(int)
        try:
            영업자산 = (자산_비영업포함 -유동금융자산-현금및현금성자산-투자부동산-장기금융자산-관계기업등지분관련투자자산 - 기타금융업자산).astype(int)
        except:
            print('영업자산 뭔가 이상함')
            return [np.nan,np.nan,np.nan,np.nan]
        
        ock_수식 = 영업이익/영업자산 * 100
        return ock_수식

        


    def __del__(self):
        print(self.stock_code+'가 종료')